---
- name: Create workdir
  ansible.builtin.file:
    path: '/home/ubuntu/prestashop'
    state: directory
    mode: '0755'

- name: Copy files in workdir
  ansible.builtin.copy:
    src: ../files/
    dest: '/home/ubuntu/prestashop/'
    directory_mode:
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create directories for attach volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
  - '/home/ubuntu/prestashop/volumes'
  - '/home/ubuntu/prestashop/volumes/db'
  - '/home/ubuntu/prestashop/volumes/db/mysql'
  - '/home/ubuntu/prestashop/volumes/db/mysql/data'
  - '/home/ubuntu/prestashop/volumes/db/mysql/logs'
  - '/home/ubuntu/prestashop/volumes/db/mysql/init'
  - '/home/ubuntu/prestashop/volumes/web'
  - '/home/ubuntu/prestashop/volumes/web/modules'
  - '/home/ubuntu/prestashop/volumes/web/themes'
  - '/home/ubuntu/prestashop/volumes/web/override'

- name: Create and start services
  community.docker.docker_compose:
    project_src: '/home/ubuntu/prestashop'
  register: output
  environment: 
    IP_ADDRESS: '{{ ip_host }}'

- name: Show results
  ansible.builtin.debug:
    var: output
