---
- hosts: "{{ code_app }}"
  become: yes
  tasks:
    - name: Change COMPOSE_HTTP_TIMEOUT and DOCKER_CLIENT_TIMEOUT
      shell: |
        set -o pipefail
        export DOCKER_CLIENT_TIMEOUT=480
        export COMPOSE_HTTP_TIMEOUT=480
      args:
        executable: /bin/bash
  tasks:
    - name: deploy dolibarr app
      include_role:
        name: dolibarr
      when: app_name == "erp"
    
    - name: deploy orangehrm app
      include_role:
        name: hrm
      when: app_name == "hrm"

    - name: deploy prestashop app
      include_role:
        name: prestashop
      when: app_name == "e-commerce"

- hosts: localhost
  tasks:
    - name: Clean local workdir
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "ssh_key_{{ code_app }}.pem"
  
