---
- hosts: "{{ code_app }}"
  become: yes
  tasks:
    - name: deploy dolibarr app
      include_role:
        name: dolibarr
      environment: 
        DOCKER_CLIENT_TIMEOUT: 480
        COMPOSE_HTTP_TIMEOUT: 480
      when: app_name == "erp"
    
    - name: deploy orangehrm app
      include_role:
        name: hrm
      environment: 
        DOCKER_CLIENT_TIMEOUT: 480
        COMPOSE_HTTP_TIMEOUT: 480
      when: app_name == "hrm"

    - name: deploy prestashop app
      include_role:
        name: prestashop
      environment: 
        DOCKER_CLIENT_TIMEOUT: 480
        COMPOSE_HTTP_TIMEOUT: 480
      when: app_name == "e-commerce"

- hosts: localhost
  tasks:
    - name: Clean local workdir
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "ssh_key_{{ code_app }}.pem"
  
