version: '3.9'
services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop_dev
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - ./volumes/db/mysql/data/:/var/lib/mysql
      - ./volumes/db/mysql/logs/:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - prestashop-net


  prestashop:
    image: prestashop/prestashop:1.7
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop_dev
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - PS_DOMAIN=${IP_ADDRESS}:8080
      - DB_PREFIX=ps_
      - ADMIN_MAIL=demo@coridigital.com
      - ADMIN_PASSWD=coridigital_demo
      - PS_LANGUAGE=fr
      - PS_COUNTRY=SN
      - PS_ALL_LANGUAGES=0
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=1
      - PS_INSTALL_DB=1
      - PS_DEV_MODE=1
      - PS_HOST_MODE=1
      - PS_DEMO_MODE=1
      - PS_HANDLE_DYNAMIC_DOMAIN=0
      - PS_FOLDER_ADMIN=admin-ans
      - PS_FOLDER_INSTALL=install-ans
      - PS_ENABLE_SSL=0
    volumes:
      - ./volumes/web/:/var/www/html
      - ./volumes/web/modules/:/var/www/html/modules
      - ./volumes/web/themes/:/var/www/html/themes
      - ./volumes/web/override/:/var/www/html/override
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - prestashop-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${IP_ADDRESS}:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   restart: always
  #   volumes:
  #     - ./volume/nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./volume/certbot/www:/var/www/certbot/:ro
  #   networks:
  #     - prestashop-net

  # certbot:
  #   image: certbot/certbot:latest
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   volumes:
  #     - ./volumevolume/certbot/www/:/var/www/certbot/:rw
  #     - ./volume/certbot/conf/:/etc/letsencrypt/:rw
  #   networks:
  #     - prestashop-net

networks:
  prestashop-net: