---
- name: Create workdir
  ansible.builtin.file:
    path: /home/ubuntu/orangehrm
    state: directory
    mode: '0755'

- name: Copy files in workdir
  ansible.builtin.copy:
    src: ../files/
    dest: /home/ubuntu/orangehrm/
    directory_mode:
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create directories for attach volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
  - /home/ubuntu/orangehrm/volumes
  - /home/ubuntu/orangehrm/volumes/db
  - /home/ubuntu/orangehrm/volumes/db/mysql
  - /home/ubuntu/orangehrm/volumes/db/mysql/data
  - /home/ubuntu/orangehrm/volumes/db/mysql/logs
  - /home/ubuntu/orangehrm/volumes/db/mysql/init
  - /home/ubuntu/orangehrm/volumes/web/

- name: Create and start services
  community.docker.docker_compose:
    project_src: /home/ubuntu/orangehrm
  register: output
  environment: 
    DOCKER_CLIENT_TIMEOUT: '480'
    COMPOSE_HTTP_TIMEOUT: '480'

- name: Show results
  ansible.builtin.debug:
    var: output