---
- name: Create workdir
  ansible.builtin.file:
    path: /home/ubuntu/dolibarr
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: Copy files in workdir
  ansible.builtin.copy:
    src: ../files/
    dest:  /home/ubuntu/dolibarr/
    directory_mode:
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Create directories for attach volumes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  with_items:
  - /home/ubuntu/dolibarr/volumes
  - /home/ubuntu/dolibarr/volumes/db
  - /home/ubuntu/dolibarr/volumes/db/mariadb
  - /home/ubuntu/dolibarr/volumes/web/
  - /home/ubuntu/dolibarr/volumes/web/documents
  - /home/ubuntu/dolibarr/volumes/web/html
  - /home/ubuntu/dolibarr/volumes/web/scripts

- name: Create and start services
  community.docker.docker_compose:
    project_src: /home/ubuntu/dolibarr
  register: output
  environment: 
    DOLI_IMAGE_TAG: '{{ DOLI_IMAGE_TAG }}'
    IP_ADDRESS: '{{ ip_host }}'
    DOCKER_CLIENT_TIMEOUT: '480'
    COMPOSE_HTTP_TIMEOUT: '480'

- name: Show results
  ansible.builtin.debug:
    var: output